import assert from "node:assert/strict";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { createHash, randomUUID as uuid } from "node:crypto";
import postgres from "../build-7/node_modules/postgres/src/index.js";
const db = postgres("postgres://postgres@127.0.0.1:55441/build8", {
  max: 1,
  prepare: false,
  onnotice: () => {},
});
const evidence = {
  scope: "disposable atomic-ledger synthetic target class only",
  stage: "composition, not full P01-P14 proof",
};
const definition = async () =>
  (await db`select pg_get_functiondef('public.prepare_build_5b_artifact()'::regprocedure) definition`)[
    0
  ].definition;
try {
  const before = await definition();
  const request = uuid();
  await db`insert into public.artifacts(id,artifact_role,context_id) values(${request}::uuid,'transformation_request','8777e33d-7555-40aa-92f9-d5107395c0c7')`;
  await db.begin(async (tx) =>
    tx.unsafe(
      readFileSync(
        "sql/migrations/20260911130000_build_8_action_envelope.sql",
        "utf8",
      ),
    )
  );
  assert.equal(await definition(), before);
  const output = uuid(), attempt = uuid();
  // Exact retained positive output is frozen BUILD 5B fixture data, not generated by this checker.
  const [{ payload_text: positive }] =
    await db`select payload_text from public.artifacts where id='95b5db1d-cb79-439b-ae93-0bdaef5cfda2'`;
  await db`insert into public.artifacts(id,artifact_role,context_id,payload_text,producer_succeeded) values(${output}::uuid,'transformed_representation',${request}::uuid,${positive},true)`;
  await db`insert into public.artifacts(id,artifact_role,context_id,target_id) values(${attempt}::uuid,'check_attempt',${request}::uuid,${output}::uuid)`;
  const [r] =
    await db`insert into public.artifacts(id,artifact_role,context_id) values(${uuid()}::uuid,'transformation_receipt',${attempt}::uuid) returning payload_text`;
  evidence.historical_binding = {
    request,
    output,
    attempt,
    receipt: JSON.parse(r.payload_text),
    definition_sha256: createHash("sha256").update(before).digest("hex"),
  };
  assert.equal(evidence.historical_binding.receipt.result, "PASS");
  const roles = [
    "source_representation",
    "transformation_request",
    "transformed_representation",
    "check_attempt",
    "transformation_receipt",
    "b7_grammar",
    "b7_snapshot",
    "b7_contract",
    "b7_candidate",
    "b7_attempt",
    "b7_evaluation",
    "b7_grant",
    "b7_designation",
    "b7_observation",
    "b8_basis",
    "b8_envelope",
    "b8_evaluation",
    "b8_event",
  ];
  // Trigger WHEN expressions use OLD/NEW range-table entries; pg_get_expr cannot
  // deparse these as a single relation. Use PostgreSQL's trigger-aware deparser.
  const triggers =
    await db`select tgname,pg_get_triggerdef(oid) definition from pg_trigger where tgrelid='public.artifacts'::regclass and not tgisinternal and (tgtype & 2)=2 and (tgtype & 4)=4`;
  evidence.routing = [];
  for (const role of roles) {
    const hits = [];
    for (const t of triggers) {
      // Evaluate actual catalog predicate for each accepted role, not a rewritten routing mirror.
      const predicate = t.definition.match(/ WHEN \((.*)\) EXECUTE FUNCTION /)
        ?.[1];
      const pred =
        predicate?.replaceAll("new.artifact_role", "probe.artifact_role") ??
          "true";
      const [match] = await db.unsafe(
        `select (${pred}) matches from (select $1::text artifact_role) probe`,
        [role],
      );
      if (match.matches) hits.push(t.tgname);
    }
    evidence.routing.push({ role, hits });
    assert.equal(hits.length, 1);
  }
  const [privileges] =
    await db`select has_column_privilege('ecb8_owner','ecb7.scopes','current_event','UPDATE') pointer,has_table_privilege('ecb8_owner','ecb7.scopes','UPDATE') general_update,has_column_privilege('ecb8_owner','ecb7.scopes','synthetic','UPDATE') lock_column,rolcanlogin,rolinherit from pg_roles where rolname='ecb8_owner'`;
  assert.deepEqual(privileges, {
    pointer: false,
    general_update: false,
    lock_column: true,
    rolcanlogin: false,
    rolinherit: false,
  });
  evidence.custody = privileges;
  await assert.rejects(
    db.begin(async (tx) => {
      await tx`set local role ecb8_owner`;
      await tx`update ecb7.scopes set current_event=null`;
    }),
    /permission denied/,
  );
  await assert.rejects(
    db.begin("isolation level repeatable read", async (tx) => {
      await tx`set local role ecb8_owner`;
      await tx`select ecb8.lock_scope(${uuid()}::uuid)`;
    }),
    /b8_read_committed_required/,
  );
  evidence.result = "PASS";
  console.log(JSON.stringify(evidence, null, 2));
} catch (e) {
  evidence.result = "FAIL";
  evidence.error = e.message;
  throw e;
} finally {
  mkdirSync("docs/build-receipts/evidence/build-8", { recursive: true });
  writeFileSync(
    "docs/build-receipts/evidence/build-8/composition.json",
    JSON.stringify(evidence, null, 2) + "\n",
  );
  await db.end();
}
