import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { setTimeout as delay } from "node:timers/promises";
import * as t from "./support.mjs";
import { recover } from "../../server/build-8/recover.mjs";
const {
  admin,
  actor,
  observer,
  evaluator,
  b7,
  make,
  ready,
  started,
  propose,
  qualify,
  grant,
  authorize,
  control,
  env,
  inspect,
  head,
  uuid,
} = t;
const results = [], controls = [];
const copy = structuredClone;
async function reject(name, fn, pattern = /b8_|permission denied|no rows/) {
  let error;
  try {
    await fn();
  } catch (e) {
    error = e.message;
  }
  assert.ok(error, `${name}: unexpected success`);
  assert.match(error, pattern);
  controls.push({ name, error });
  return error;
}
async function qcase(f, name, mutate, want) {
  const c = copy(f.candidate);
  mutate(c);
  const id = await propose(f, c), q = await qualify(f, id);
  assert.equal(q.outcome, want, `${name}: ${JSON.stringify(q)}`);
  controls.push({ name, expected: want, envelope: id, evaluation: q });
  return { id, q };
}
async function count(f, n) {
  const s = await inspect(f);
  assert.equal(s.history?.effects.length, n, JSON.stringify(s));
  return s;
}
async function group(id, fn) {
  if (process.env.B8_GROUPS && !process.env.B8_GROUPS.split(",").includes(id)) {
    return;
  }
  const before = controls.length;
  try {
    const value = await fn();
    results.push({
      id,
      outcome: "PASS",
      controls: controls.slice(before),
      value,
    });
    console.log(`${id} PASS (${controls.length - before} controls)`);
  } catch (e) {
    results.push({
      id,
      outcome: "FAIL",
      classification:
        "implementation failure or invalid test; inspect retained error before disposition",
      error: e.stack,
      controls: controls.slice(before),
    });
    console.error(`${id} FAIL: ${e.stack}`);
    throw e;
  } finally {
    t.save("primary.json", {
      proof_class: "atomic-ledger synthetic target only",
      authorship:
        "same worker designed implementation and tests; expected values fixed in tests, not generated by checker",
      results,
    });
  }
}
// Test barriers hold real transactions. Driver knows commit/abort; reader receives
// only locator and cannot see the branch decision. No doctored reader or sleep race.
async function heldEffect(f, st, { abort = false } = {}) {
  const db = t.connect(), p = await head(f), request = uuid();
  let release, entered, failed;
  const gate = new Promise((r) => release = r),
    entry = new Promise((r, j) => {
      entered = r;
      failed = j;
    });
  const work = db.begin("isolation level read committed", async (tx) => {
    const result = await control(f, "effect", st, { db: tx, p, request });
    entered(result);
    await gate;
    if (abort) throw Error("TEST_ROLLBACK_EFFECT");
    return result;
  }).catch((e) => {
    failed(e);
    if (abort && e.message === "TEST_ROLLBACK_EFFECT") return { aborted: true };
    throw e;
  }).finally(() => db.end());
  const result = await entry;
  return { release, work, result, p, request };
}
async function lockWait() {
  const stats = t.connect("custodian");
  try {
    const deadline = Date.now() + 5000;
    while (Date.now() < deadline) {
      const [r] =
        await stats`select count(*)::int n from pg_stat_activity where datname='build8' and usename='b8_actor' and wait_event_type='Lock'`;
      if (r.n) return;
      await delay(10);
    }
    throw Error("TEST_INVALID: waiter never reached real lock");
  } finally {
    await stats.end();
  }
}
async function corrupt(f, fn) {
  const db = t.connect("custodian");
  try {
    return await db.begin(async (tx) => {
      await tx`set local session_replication_role=replica`;
      let value;
      await tx.savepoint(async (sp) => {
        value = await fn(sp);
        throw Object.assign(Error("ROLLBACK_FAULT"), { value });
      }).catch((e) => {
        if (e.message !== "ROLLBACK_FAULT") throw e;
        value = e.value;
      });
      return value;
    });
  } finally {
    await db.end();
  }
}

try {
  await group("P01", async () => {
    const none = await make();
    await reject(
      "no authorization cannot admit",
      () => control(none, "admit", uuid()),
    );
    await count(none, 0);
    const f = await make(), r = await started(f);
    await count(f, 0);
    await control(f, "effect", r.st);
    const recovered = await recover(observer, f.scope, f.action);
    assert.equal(recovered.native.effect_count, 1);
    assert.equal(recovered.native.value, 1);
    assert.equal(recovered.legitimate, true);
    t.save("cold-input.json", {
      scope: f.scope,
      action: f.action,
      boundary: "ecb8-disposable-55441/build8",
    });
    const child = spawnSync(process.execPath, [
      "tests/build-8/cold.mjs",
      "docs/build-receipts/evidence/build-8/cold-input.json",
      "docs/build-receipts/evidence/build-8/cold-output.json",
    ], { encoding: "utf8" });
    assert.equal(child.status, 0, child.stderr);
    const cold = JSON.parse(
      readFileSync("docs/build-receipts/evidence/build-8/cold-output.json"),
    );
    assert.deepEqual(cold.native, {
      value: 1,
      revision: 1,
      ready: true,
      effect_count: 1,
    });
    assert.equal(cold.retry, "HOLD");
    assert.equal(cold.legitimate, true);
    return {
      scope: f.scope,
      action: f.action,
      stage: r,
      cold: { status: cold.status, native: cold.native, retry: cold.retry },
    };
  });
  await group("P02", async () => {
    const f = await make();
    for (
      const [name, mut] of Object.entries({
        actor: (c) => c.actor = uuid(),
        target: (c) => c.target = uuid(),
        target_revision: (c) => c.target_revision = 1,
        method: (c) => c.method = "0".repeat(64),
        orientation_key: (c) => c.orientation.key = uuid(),
        orientation_evaluation: (c) => c.orientation.evaluation = uuid(),
        source_version: (c) =>
          c.dependencies[f.orientation.snapshots[1]].revision = "2",
      })
    ) await qcase(f, name, mut, "FAIL");
    for (const field of ["scope", "action"]) {
      await reject(
        `${field} valid UUID wrong locator`,
        () => propose(f, { ...f.candidate, [field]: uuid() }),
      );
    }
    const id = await propose(f),
      q = await qualify(f, id),
      g = await grant(f, id, q);
    await reject(
      "protected wrong authentication basis",
      () => authorize(f, id, q, g, null, t.other),
    );
    const second = await propose(f);
    await reject(
      "evaluation for different exact envelope",
      () => authorize(f, second, q, g),
    );
    for (
      const [field, val] of Object.entries({
        actor: uuid(),
        action: uuid(),
        target: uuid(),
        scope: uuid(),
        envelope: uuid(),
        evaluation: uuid(),
        predecessor: uuid(),
        login: "b8_other",
        operation: "advance_two",
      })
    ) {
      // Wrong scope/action fixtures are separately addressed, not allowed to escape locator.
      if (["scope", "action"].includes(field)) {
        await reject(
          `grant ${field} escape`,
          () => grant(f, id, q, null, { [field]: val }),
        );
        continue;
      }
      const bad = await grant(f, id, q, null, { [field]: val });
      await reject(`grant ${field} mismatch`, () => authorize(f, id, q, bad));
    }
    await reject(
      "wrong full-history predecessor",
      () => authorize(f, id, q, g, null, actor, uuid()),
    );
    await authorize(f, id, q, g);
    await count(f, 0);
    return { scope: f.scope };
  });
  await group("P03", async () => {
    const f = await make();
    await qcase(f, "canonical expression", () => {}, "PASS");
    await qcase(
      f,
      "interpreted paraphrase",
      (c) => c.expression = f.paraphrase,
      "PASS",
    );
    for (
      const [name, mut] of Object.entries({
        wrong_increment: (c) => c.delta = 2,
        wrong_maximum: (c) => c.max_effects = 2,
        wrong_access: (c) => c.observation_access = "native",
        contradictory_expression: (c) => c.expression = f.wrong,
        native_discrimination: (c) =>
          c.expression = "The native sensor supplies the discrimination",
      })
    ) await qcase(f, name, mut, "FAIL");
    await qcase(
      f,
      "unsupported wording",
      (c) => c.expression = "Please do the clever calibration thing",
      "INCOMPLETE",
    );
    await qcase(
      f,
      "unresolved comparator",
      (c) => c.expression = "Comparator has no resolved interpretation",
      "INDETERMINATE",
    );
    await qcase(
      f,
      "recognized wrong target meaning",
      (c) => c.expression = "Advance a different target by one",
      "FAIL",
    );
    await qcase(f, "FAIL precedence over unsupported wording", (c) => {
      c.expression = "Uninterpreted";
      c.delta = 2;
    }, "FAIL");
    return { scope: f.scope };
  });
  await group("P04", async () => {
    const f = await make();
    for (const id of Object.keys(f.candidate.dependencies)) {
      await qcase(
        f,
        `missing required dependency ${id}`,
        (c) => delete c.dependencies[id],
        "INCOMPLETE",
      );
    }
    await qcase(
      f,
      "valid wrong digest",
      (c) => c.dependencies[f.orientation.snapshots[1]].digest = "a".repeat(64),
      "FAIL",
    );
    await qcase(
      f,
      "expression-only change",
      (c) => c.expression = f.wrong,
      "FAIL",
    );
    const id = await propose(f);
    const missing = await corrupt(f, async (tx) => {
      await tx`delete from public.artifacts where id=${
        f.orientation.snapshots[1]
      }::uuid`;
      const [r] =
        await tx`select ecb8.examine(${id}::uuid,${f.contract}::uuid) q`;
      assert.equal(r.q.outcome, "INCOMPLETE");
      return r.q;
    });
    controls.push({
      name: "digest retained but native payload removed",
      evaluation: missing,
    });
    await env(f, "dependency", { source: uuid(), revision: "unrelated-2" });
    const q = await qualify(f, id);
    assert.equal(q.outcome, "PASS");
    controls.push({
      name: "unrelated source does not invalidate",
      evaluation: q,
    });
    return { scope: f.scope };
  });
  await group("P05", async () => {
    const f = await make(), id = await propose(f), q = await qualify(f, id);
    await count(f, 0);
    await reject("qualified is not authorized", () => control(f, "admit", id));
    await reject("absent grant", () => authorize(f, id, q, uuid()));
    for (const role of ["b8_basis", "b8_evaluation", "b8_event"]) {
      await reject(
        `direct forged ${role}`,
        () =>
          b7.producer`insert into public.artifacts(id,artifact_role,context_id,payload_text) values(${uuid()}::uuid,${role},${f.scope}::uuid,${
            JSON.stringify({ scope: f.scope, action: f.action })
          })`,
        /b8_|permission denied/,
      );
    }
    await reject(
      "producer cannot publish evaluation",
      async () =>
        b7.producer`select ecb8.qualify(${f.scope}::uuid,${f.action}::uuid,${id}::uuid,${f.contract}::uuid,${await head(
          f,
        )}::uuid)`,
    );
    await reject(
      "evaluator cannot invoke authority",
      () => authorize(f, id, q, uuid(), null, evaluator),
    );
    const bad = await qcase(
        f,
        "failed qualification remains ineligible",
        (c) => c.delta = 2,
        "FAIL",
      ),
      bg = await grant(f, bad.id, bad.q);
    await reject(
      "matching grant cannot promote FAIL",
      () => authorize(f, bad.id, bad.q, bg),
    );
    const g = await grant(f, id, q);
    await reject(
      "BUILD 7 designation not action evaluation",
      () => authorize(f, id, { id: f.candidate.orientation.designation }, g),
    );
    await authorize(f, id, q, g);
    await count(f, 0);
    return { scope: f.scope };
  });
  await group("P06", async () => {
    const f = await make(), r = await ready(f);
    const newer = await propose(f);
    assert.equal((await inspect(f)).history.selected.envelope, r.id);
    const q2 = await qualify(f, newer), g2 = await grant(f, newer, q2, r.au);
    await reject(
      "replacement requires actual selection predecessor",
      () => authorize(f, newer, q2, g2, null),
    );
    const replacement = await authorize(f, newer, q2, g2, r.au);
    assert.equal((await inspect(f)).history.selected.envelope, newer);
    for (
      const stage of ["qualification", "authorization", "admission", "effect"]
    ) {
      const x = await make();
      const id = await propose(x),
        q = await qualify(x, id),
        g = await grant(x, id, q);
      let au, st;
      if (["admission", "effect"].includes(stage)) {
        au = (await authorize(x, id, q, g)).event;
      }
      if (stage === "effect") {
        const ad = await control(x, "admit", au);
        st = (await control(x, "start", ad.event)).event;
      }
      await env(x, "dependency", {
        source: x.orientation.snapshots[1],
        revision: "2",
      });
      if (stage === "qualification") {
        const changed = await qualify(x, id);
        assert.equal(changed.outcome, "FAIL");
        controls.push({
          name: "basis changed before qualification",
          evaluation: changed,
        });
      }
      if (stage === "authorization") {
        await reject(
          "basis drift before authorization",
          () => authorize(x, id, q, g),
        );
      }
      if (stage === "admission") {
        await reject(
          "basis drift before admission",
          () => control(x, "admit", au),
        );
      }
      if (stage === "effect") {
        await reject(
          "basis drift before effect",
          () => control(x, "effect", st),
        );
      }
      await count(x, 0);
    }
    const x = await make(), sr = await started(x);
    await env(x, "ready", { ready: false });
    await env(x, "ready", { ready: true });
    assert.equal((await inspect(x)).history.revision, 2);
    await reject(
      "target change-away/back revision",
      () => control(x, "effect", sr.st),
    );
    const y = await make(), yr = await started(y);
    const o = await b7.observe(y.orientation);
    const key = {
      id: y.candidate.orientation.key,
      result: { id: y.candidate.orientation.evaluation },
    };
    const wg = await b7.grant(
      y.orientation,
      key,
      y.candidate.orientation.designation,
      { operation: "withdraw" },
    );
    await b7.select(
      y.orientation,
      key,
      y.candidate.orientation.designation,
      wg,
      o,
      uuid(),
      "withdraw",
    );
    await reject(
      "BUILD 7 selection drift before effect",
      () => control(y, "effect", yr.st),
    );
    return { replacement: replacement.event };
  });
  await group("P07", async () => {
    const f = await make(), r = await ready(f);
    await env(f, "tick", { tick: 19 });
    const ad = await control(f, "admit", r.au);
    await env(f, "tick", { tick: 20 });
    await reject("new admission at 20", () => control(f, "admit", r.au));
    const st = await control(f, "start", ad.event);
    await env(f, "tick", { tick: 21 });
    await control(f, "effect", st.event);
    await env(f, "revoke_grant", { grant: r.g });
    await env(f, "tick", { tick: 30 });
    const rec = await recover(observer, f.scope, f.action);
    assert.equal(rec.legitimate, true);
    assert.equal(rec.present.applicable, false);
    const late = await make();
    await env(late, "tick", { tick: 12 });
    const id = await propose(late),
      q = await qualify(late, id),
      g = await grant(late, id, q);
    await reject("authorization at 12", () => authorize(late, id, q, g));
    const end = await make(), er = await started(end);
    await env(end, "tick", { tick: 30 });
    await reject("effect at 30", () => control(end, "effect", er.st));
    const before = await head(end);
    assert.equal((await inspect(end)).status, "RECONCILE_REQUIRED");
    assert.equal(await head(end), before);
    await control(end, "reconcile", er.st);
    for (const stage of ["admission", "effect"]) {
      const x = await make(), rr = await ready(x);
      let st;
      if (stage === "effect") {
        const ad = await control(x, "admit", rr.au);
        st = (await control(x, "start", ad.event)).event;
      }
      await env(x, "revoke_grant", { grant: rr.g });
      await reject(
        `revocation before ${stage}`,
        () => control(x, stage, stage === "admission" ? rr.au : st),
      );
    }
    await reject(
      "tick cannot move backward",
      () => env(f, "tick", { tick: 29 }),
    );
    await reject(
      "tick cannot remain equal",
      () => env(f, "tick", { tick: 30 }),
    );
    return { historical_legitimate: rec.legitimate, present: rec.present };
  });
  await group("P08", async () => {
    const f = await make(), r = await ready(f);
    const ad = await control(f, "admit", r.au);
    await count(f, 0);
    await env(f, "ready", { ready: false });
    await reject(
      "target drift after admission",
      () => control(f, "start", ad.event),
    );
    // For each condition, commit-first effect remains historical; change-first blocks.
    for (const k of ["ready", "revoke_grant", "tick"]) {
      const x = await make(),
        st = await started(x),
        held = await heldEffect(x, st.st);
      let mutation;
      const pending = (async () => {
        const db = t.connect("postgres");
        try {
          const d = k === "ready"
            ? { ready: false }
            : k === "tick"
            ? { tick: 30 }
            : { grant: st.g };
          mutation =
            (await db`select ecb8.fixture_event(${x.scope}::uuid,${x.action}::uuid,${k},${
              db.json(d)
            },${held.result.event}::uuid) id`)[0].id;
        } finally {
          await db.end();
        }
      })();
      held.release();
      await held.work;
      await pending;
      assert.equal(
        (await recover(observer, x.scope, x.action)).legitimate,
        true,
      );
      controls.push({ name: `effect serialized before ${k}`, mutation });
    }
    return { admission_only: ad.event };
  });
  await group("P09", async () => {
    const f = await make(), r = await ready(f), p = await head(f);
    await reject(
      "rollback admission transaction",
      () =>
        actor.begin(async (tx) => {
          await control(f, "admit", r.au, { db: tx, p });
          throw Error("TEST_ABORT");
        }),
      /TEST_ABORT/,
    );
    assert.equal(await head(f), p);
    const ad = await control(f, "admit", r.au);
    assert.equal(
      (await inspect(f)).history.starts &&
        Object.keys((await inspect(f)).history.starts).length,
      0,
    );
    await reject(
      "uncommitted start cannot effect",
      () =>
        actor.begin(async (tx) => {
          const st = await control(f, "start", ad.event, {
            db: tx,
            p: ad.event,
          });
          await control(f, "effect", st.event, { db: tx, p: st.event });
        }),
      /b8_committed_start_required/,
    );
    const st = await control(f, "start", ad.event);
    assert.equal((await inspect(f)).status, "RECONCILE_REQUIRED");
    const held = await heldEffect(f, st.event, { abort: true });
    held.release();
    await held.work;
    assert.equal((await inspect(f)).status, "RECONCILE_REQUIRED");
    await reject(
      "fresh admission before explicit fence",
      () => control(f, "admit", r.au),
    );
    const fenced = await control(f, "reconcile", st.event);
    await reject(
      "late old executor cannot bypass fence",
      () => control(f, "effect", st.event),
    );
    const ad2 = await control(f, "admit", r.au),
      st2 = await control(f, "start", ad2.event);
    await control(f, "effect", st2.event);
    await count(f, 1);
    return { started: st.event, fence: fenced.event, fresh_start: st2.event };
  });
  await group("P10", async () => {
    const f = await make(),
      r = await started(f),
      held = await heldEffect(f, r.st);
    const waiter = t.connect();
    let settled = false;
    const attempt = control(f, "effect", r.st, { db: waiter, p: held.p }).then(
      (v) => {
        settled = true;
        return { value: v };
      },
      (e) => {
        settled = true;
        return { error: e.message };
      },
    );
    await lockWait(waiter);
    assert.equal(settled, false);
    held.release();
    await held.work;
    const got = await attempt;
    await waiter.end();
    // This assertion is the accepted E5 falsifier: do not repair via a harness snapshot.
    assert.equal(
      got.error,
      "b8_effect_allowance_consumed",
      "E5 MECHANISM-DESIGN FALSIFICATION: actual READ COMMITTED waiter failed to observe commit",
    );
    controls.push({
      name: "READ COMMITTED locked waiter sees committed competitor",
      ...got,
    });
    await count(f, 1);
    const rr = await control(f, "effect", r.st, {
      p: held.p,
      request: held.request,
    });
    assert.equal(rr.replayed, true);
    await count(f, 1);
    for (const op of ["admit", "effect", "reconcile"]) {
      await reject(
        `REPEATABLE READ rejects ${op}`,
        () =>
          actor.begin(
            "isolation level repeatable read",
            (tx) => control(f, op, r.st, { db: tx, p: held.result.event }),
          ),
        /b8_read_committed_required/,
      );
    }
    const r2 = await make(),
      ar = await ready(r2),
      ad1 = await control(r2, "admit", ar.au),
      ad2 = await control(r2, "admit", ar.au),
      p2 = await head(r2);
    const db1 = t.connect(), db2 = t.connect();
    try {
      const pair = await Promise.allSettled([
        control(r2, "start", ad1.event, { db: db1, p: p2 }),
        control(r2, "start", ad2.event, { db: db2, p: p2 }),
      ]);
      assert.equal(pair.filter((x) => x.status === "fulfilled").length, 1);
      controls.push({
        name: "different requests one unresolved start",
        outcomes: pair.map((x) => x.status),
      });
    } finally {
      await db1.end();
      await db2.end();
    }
    // A rollback contender must leave a waiter free to perform the first effect.
    const rb = await make(),
      br = await started(rb),
      holder = await heldEffect(rb, br.st, { abort: true });
    const w = t.connect();
    const pending = control(rb, "effect", br.st, { db: w, p: holder.p });
    await lockWait(w);
    holder.release();
    await holder.work;
    const winner = await pending;
    await w.end();
    await count(rb, 1);
    controls.push({ name: "rollback contender does not stale waiter", winner });
    const newer = await propose(f),
      nq = await qualify(f, newer),
      ng = await grant(f, newer, nq, r.au);
    await authorize(f, newer, nq, ng, r.au);
    await reject(
      "replacement envelope does not reset occurrence",
      async () => control(f, "admit", (await inspect(f)).history.selected.id),
    );
    return { waiter: got, one_effect: 1 };
  });
  await group("P11", async () => {
    const f = await make(), r = await started(f);
    const held = await heldEffect(f, r.st);
    held.release();
    await held.work; // Deliberately do not publish ACK observation.
    const rec = await recover(observer, f.scope, f.action);
    assert.equal(rec.native.effect_count, 1);
    assert.equal(rec.acks.length, 0);
    assert.equal(rec.retry, "HOLD");
    await reject(
      "new request after lost ACK",
      () => control(f, "effect", r.st),
    );
    const no = await make(), nr = await started(no);
    await observer`select ecb8.ack(${no.scope}::uuid,${no.action}::uuid,${nr.st}::uuid,${uuid()}::uuid,true,${await head(
      no,
    )}::uuid)`;
    const falseAck = await recover(observer, no.scope, no.action);
    assert.equal(falseAck.native.effect_count, 0);
    assert.equal(falseAck.acks.length, 1);
    assert.equal(falseAck.status, "RECONCILE_REQUIRED");
    return {
      lost_ack: { effects: 1, acks: 0 },
      false_ack: { effects: 0, acks: 1 },
    };
  });
  await group("P12", async () => {
    const branches = [];
    for (const abort of [false, true]) {
      const f = await make(),
        r = await started(f),
        held = await heldEffect(f, r.st, { abort });
      const states = await Promise.all(Array.from({ length: 24 }, async () => {
        const db = t.connect("b8_observer");
        try {
          return await recover(db, f.scope, f.action);
        } finally {
          await db.end();
        }
      }));
      assert.ok(
        states.every((s) =>
          s.status === "UNKNOWN / IN_FLIGHT" && s.retry === "HOLD" &&
          s.fence === null
        ),
      );
      held.release();
      await held.work;
      const after = await recover(observer, f.scope, f.action);
      if (abort) {
        assert.equal(after.status, "RECONCILE_REQUIRED");
        const before = await head(f);
        for (let i = 0; i < 8; i++) await inspect(f);
        assert.equal(await head(f), before);
        await reject(
          "unknown then no-effect does not grant retry",
          () => control(f, "admit", r.au),
        );
        const fence = await control(f, "reconcile", r.st);
        await reject(
          "fence wins delayed execution",
          () => control(f, "effect", r.st),
        );
        branches.push({
          abort,
          unknown: states[0],
          after: after.status,
          fence: fence.event,
        });
      } else {
        assert.equal(after.native.effect_count, 1);
        assert.equal(after.legitimate, true);
        assert.equal(after.ordered.filter((e) => e.kind === "fence").length, 0);
        branches.push({
          abort,
          unknown: states[0],
          after: after.status,
          native: after.native,
        });
      }
    }
    assert.deepEqual(branches[0].unknown, branches[1].unknown);
    controls.push({
      name: "real hidden commit/abort branches and 48-reader replay storm",
      branches,
    });
    return branches;
  });
  await group("P13", async () => {
    const f = await make(), r = await started(f);
    await control(f, "effect", r.st);
    const defects = [];
    for (
      const [name, id] of [["method contract", f.contract], [
        "required source",
        f.orientation.snapshots[1],
      ], ["event predecessor", r.ad]]
    ) {
      const value = await corrupt(f, async (tx) => {
        await tx`delete from public.artifacts where id=${id}::uuid`;
        return recover(tx, f.scope, f.action);
      });
      assert.equal(value.status, "UNKNOWN");
      assert.equal(value.retry, "HOLD");
      defects.push({ name, status: value.status, reason: value.reason });
    }
    const fork = await corrupt(f, async (tx) => {
      const data = await docFor(tx, r.st);
      await tx`update public.artifacts set payload_text=${
        JSON.stringify({ ...data, predecessor: uuid() })
      },payload_digest=extensions.digest(convert_to(${
        JSON.stringify({ ...data, predecessor: uuid() })
      },'UTF8'),'sha256') where id=${r.st}::uuid`;
      return recover(tx, f.scope, f.action);
    });
    assert.equal(fork.status, "UNKNOWN");
    defects.push({
      name: "broken history/digest",
      status: fork.status,
      reason: fork.reason,
    });
    // Retain a newer candidate: exact selected payload disappearance may not use it.
    await propose(f);
    const missing = await corrupt(f, async (tx) => {
      await tx`delete from public.artifacts where id=${r.id}::uuid`;
      return recover(tx, f.scope, f.action);
    });
    assert.equal(missing.status, "UNKNOWN");
    defects.push({ name: "no newest substitution", reason: missing.reason });
    controls.push(...defects);
    return { scope: f.scope, defects };
  });
  await group("P14", async () => {
    const f = await make(), r = await started(f);
    for (
      const role of ["ecb8_owner", "b8_actor", "b8_evaluator", "b8_observer"]
    ) {
      const [priv] =
        await admin`select has_column_privilege(${role},'ecb7.scopes','current_event','UPDATE') pointer,has_table_privilege(${role},'ecb7.scopes','UPDATE') general_update,pg_has_role(${role},'ecb7_owner','MEMBER') inherited7`;
      assert.deepEqual(priv, {
        pointer: false,
        general_update: false,
        inherited7: false,
      });
      controls.push({ name: `custody ${role}`, priv });
    }
    await reject(
      "BUILD 8 owner cannot update pointer",
      () =>
        admin.begin(async (tx) => {
          await tx`set local role ecb8_owner`;
          await tx`update ecb7.scopes set current_event=null where id=${f.scope}::uuid`;
        }),
      /permission denied/,
    );
    await reject(
      "runtime cannot assume custody",
      () => actor`set role ecb8_owner`,
      /permission denied/,
    );
    for (const op of ["update", "delete", "truncate"]) {
      await reject(`runtime immutable ${op}`, () =>
        actor.unsafe(
          op === "update"
            ? `update public.artifacts set payload_text=payload_text where false`
            : op === "delete"
            ? `delete from public.artifacts where false`
            : `truncate public.artifacts`,
        ), /permission denied/);
    }
    const before = await head(f),
      fault = await admin.begin(async (tx) => {
        await tx`set local role ecb8_owner`;
        return (await tx`select ecb8.retain('b8_event',${f.scope}::uuid,${
          JSON.stringify({
            scope: f.scope,
            action: f.action,
            kind: "effect",
            predecessor: before,
            login: "postgres",
            participant: (await inspect(f)).history.initial.principals.postgres,
            request: uuid(),
            data: {
              start: null,
              target: f.target,
              operation: "advance_one",
              delta: 1,
              observation: {},
            },
          })
        }) id`)[0].id;
      });
    const bad = await recover(observer, f.scope, f.action);
    assert.equal(bad.status, "EFFECT_ESTABLISHED");
    assert.equal(bad.native.value, 1);
    assert.equal(bad.legitimate, false);
    await reject(
      "illegitimate effect still consumes native allowance",
      () => control(f, "effect", r.st),
    );
    controls.push({
      name:
        "privileged unauthorized increment is observed effect with failed legitimacy",
      fault,
      native: bad.native,
      legitimate: bad.legitimate,
    });
    const [schema] =
      await admin`select count(*)::int n from pg_tables where schemaname='ecb8'`;
    assert.equal(schema.n, 0);
    const [gov] =
      await admin`select (select count(*)::int from ecb_governance.scopes) scopes,(select count(*)::int from ecb_governance.decisions) decisions,(select count(*)::int from ecb_governance.transitions) transitions`;
    assert.deepEqual(gov, { scopes: 0, decisions: 0, transitions: 0 });
    return { new_tables: 0, real_governance: gov };
  });
} finally {
  await t.close();
}
async function docFor(tx, id) {
  return JSON.parse(
    (await tx`select payload_text from public.artifacts where id=${id}::uuid`)[
      0
    ].payload_text,
  );
}
